### ISSUE TITLE
Language datatype is not found (because the class is not loaded before it is used?)

### ISSUE THREAD

**Issue by turbosnute** [okhoel/RandomJoke#5]
The Joke-class doesn't seem to be loaded by the module. Datatype "language" is not found. But if I dotsource jokes.ps1, it works
<img width="752" alt="jokefail" src="https://user-images.githubusercontent.com/5786918/135887066-8fa686d1-21ec-4530-b898-5944d1e87a0d.png">
.

**Comment by okhoel** [comment]
Do you get the same error if you import ./RandomJoke/RandomJoke.psd1?

**Comment by turbosnute** [comment]
It seems like it
<img width="762" alt="jokeDatatypeFail" src="https://user-images.githubusercontent.com/5786918/135892432-93a8297a-55ce-439f-a40f-9155698aa75b.png">
(printscreen doesn't show -force on the last module load. Tried it, didn't help).

**Comment by okhoel** [comment]
It seems like there is a feature (?) that prevents a class from being loaded in a script if it contains a data type that is not yet known when the script execution starts.
